### ISSUE TITLE
help support XinGuang mesh ligh

### ISSUE THREAD

**Issue by tuzhis** [AlexxIT/XiaomiGateway3#250]
I have a xinguang mesh light. I tried to add it but still can’t control in homeassistant. please help add it or give some advice.
![image](https://user-images.githubusercontent.com/8074454/109894746-00493300-7cc9-11eb-9be1-6f2a270f9f66.png)

It is recognized as LIBMDA09X in Mi home，in gateway3，model: 2584,did: 1041479927

from  log when mi home operation brightness and color temperature，brightness 1-100，color_temp:3000-6400k

**Comment by hellkun** [comment]
insert a line
`2584: ["XinGuang", "XinGuang Smart Light", "LIBMDA09X"],`
 in core/bluetooth.py at line 41, then it should be working

**Comment by tuzhis** [comment]
> insert a line
> `2584: ["XinGuang", "XinGuang Smart Light", "LIBMDA09X"],`
> in core/bluetooth.py at line 41, then it should be working.
> You can try and report back later.

I have already made this attempt. this device is setup in the first line of the log, but it still cannot be controlled.

**Comment by AlexxIT** [comment]
Check latest master version

**Comment by tuzhis** [comment]
@AlexxIT  really appreciate your help, but still not work.
I found some differences：
a. the brightness of piid': 2 is not 1-100,
b. the value of'piid': 3 is always 6410.,no matter how the homeassistant is adjusted
c. it seems that MI HOME operator will have an extra field "tid": -1


operator in homeassistant
```shell 
2021-03-12 11:56:01  WARNING  mini_miio     192.168.4.19 | Can't send get_properties [{'did': '1041479927', 'siid': 2, 'piid': 1}]
2021-03-12 11:56:15  WARNING  mini_miio     192.168.4.19 | Can't send set_properties [{'did': '1041479927', 'siid': 2, 'piid': 2, 'value': 29555}]
2021-03-12 11:56:24  WARNING  mini_miio     192.168.4.19 | Can't send set_properties [{'did': '1041479927', 'siid': 2, 'piid': 1, 'value': False}]
2021-03-12 11:56:33  WARNING  mini_miio     192.168.4.19 | Can't send set_properties [{'did': '1041479927', 'siid': 2, 'piid': 3, 'value': 6410}]
2021-03-12 11:56:40  WARNING  mini_miio     192.168.4.19 | Can't send get_properties [{'did': '1041479927', 'siid': 2, 'piid': 1}]
2021-03-12 11:56:42  WARNING  mini_miio     192.168.4.19 | Can't send set_properties [{'did': '1041479927', 'siid': 2, 'piid': 3, 'value': 6410}]
```

operator in MI HOME
```shell
2021-03-12 11:52:34  DEBUG    gateway3      192.168.4.19 | Setup Mesh device {'did': '1041479927',  'model': 2584, 'type': 'mesh', 'device_manufacturer': 'XinGuang', 'device_name': 'XinGuang XinGuang Smart Light', 'device_model': 'LIBMDA09X', 'params': [[2, 1, 'light', 'light'], [2, 2, 'brightness', None], [2, 3, 'color_temp', None]], 'color_temp': [3000, 6400]}
2021-03-12 11:52:45  WARNING  mini_miio     192.168.4.19 | Can't send get_properties [{'did': '1041479927', 'siid': 2, 'piid': 1}]
2021-03-12 11:53:24  WARNING  mini_miio     192.168.4.19 | Can't send get_properties [{'did': '1041479927', 'siid': 2, 'piid': 1}]
2021-03-12 11:53:56  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:55.352 [D] ots: {"from":"","id":81567382,"method":"set_properties","params":[{"did":"1041479927","piid":2,"siid":2,"value":7}]}.\x1b[0m'
2021-03-12 11:53:56  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:55.382 [D] miio_client_func: method_local_broadcast_msg(), {"from":"","id":81567382,"method":"set_properties","params":[{"did":"1041479927","piid":2,"siid":2,"value":7}]}\x1b[0m'
2021-03-12 11:53:56  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:55.382 [D] miio_client_func: 3, msg: {"from":"","id":81567382,"method":"set_properties","params":[{"did":"1041479927","piid":2,"siid":2,"value":7}]},  len:111\x1b[0m'
2021-03-12 11:53:56  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:55.389 [D] miio_client_func: ot_agent_recv_handler_one(): fd:3, msg:{"id":81567382,"result":[{"did":"1041479927","siid":2,"piid":2,"code":1,"ts":1615549984,"ret":0}]}{"method":"local.query_status","params":"","id":173384} length:98 bytes\x1b[0m'
2021-03-12 11:53:56  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:55.389 [D] miio_client_func: handle_command_ack_msg: {"id":81567382,"result":[{"did":"1041479927","siid":2,"piid":2,"code":1,"ts":1615549984,"ret":0}]}{"method":"local.query_status","params":"","id":173384}\x1b[0m'
2021-03-12 11:53:56  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:55.482 [D] ots: ots_down_rpc_delegate_ack(), 195, ack: {"id":81567382,"result":[{"did":"1041479927","siid":2,"piid":2,"code":1,"ts":1615549984,"ret":0}],"exe_time":110}, len: 113\x1b[0m'
2021-03-12 11:53:56  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:55.813 [D] miio_client_func: ot_agent_recv_handler_one(): fd:3, msg:{"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":2,"value":7,"tid":-1}],"id":173385} length:112 bytes\x1b[0m'
2021-03-12 11:53:56  DEBUG    gateway3      192.168.4.19 | Process props [{'did': '1041479927', 'siid': 2, 'piid': 2, 'value': 7, 'tid': -1}]
2021-03-12 11:53:56  DEBUG    gateway3      192.168.4.19 | Process Mesh Data for 1041479927: {'brightness': 7}
2021-03-12 11:53:56  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:55.813 [D] miio_client_rpc: call={"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":2,"value":7,"tid":-1}],"id":173385}\x1b[0m'
2021-03-12 11:53:56  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:55.922 [D] ots: ots_up_rpc_delegate_out_cb(), 289, {"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":2,"value":7,"tid":-1}],"id":173385}\x1b[0m'
2021-03-12 11:53:59  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:58.315 [D] ots: {"from":"","id":9211546,"method":"set_properties","params":[{"did":"1041479927","piid":2,"siid":2,"value":1}]}.\x1b[0m'
2021-03-12 11:53:59  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:58.422 [D] miio_client_func: method_local_broadcast_msg(), {"from":"","id":9211546,"method":"set_properties","params":[{"did":"1041479927","piid":2,"siid":2,"value":1}]}\x1b[0m'
2021-03-12 11:53:59  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:58.422 [D] miio_client_func: 3, msg: {"from":"","id":9211546,"method":"set_properties","params":[{"did":"1041479927","piid":2,"siid":2,"value":1}]},  len:110\x1b[0m'
2021-03-12 11:53:59  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:58.423 [D] ots: {"from":"","id":33612776,"method":"set_properties","params":[{"did":"1041479927","piid":2,"siid":2,"value":71}]}.\x1b[0m'
2021-03-12 11:53:59  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:58.429 [D] miio_client_func: ot_agent_recv_handler_one(): fd:3, msg:{"id":9211546,"result":[{"did":"1041479927","siid":2,"piid":2,"code":1,"ts":1615550035,"ret":0}]} length:97 bytes\x1b[0m'
2021-03-12 11:53:59  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:58.429 [D] miio_client_func: handle_command_ack_msg: {"id":9211546,"result":[{"did":"1041479927","siid":2,"piid":2,"code":1,"ts":1615550035,"ret":0}]}\x1b[0m'
2021-03-12 11:53:59  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:58.453 [D] ots: ots_down_rpc_delegate_ack(), 195, ack: {"id":9211546,"result":[{"did":"1041479927","siid":2,"piid":2,"code":1,"ts":1615550035,"ret":0}],"exe_time":111}, len: 112\x1b[0m'
2021-03-12 11:53:59  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:58.542 [D] miio_client_func: method_local_broadcast_msg(), {"from":"","id":33612776,"method":"set_properties","params":[{"did":"1041479927","piid":2,"siid":2,"value":71}]}\x1b[0m'
2021-03-12 11:53:59  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:58.542 [D] miio_client_func: 3, msg: {"from":"","id":33612776,"method":"set_properties","params":[{"did":"1041479927","piid":2,"siid":2,"value":71}]},  len:112\x1b[0m'
2021-03-12 11:53:59  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:58.546 [D] miio_client_func: ot_agent_recv_handler_one(): fd:3, msg:{"id":33612776,"result":[{"did":"1041479927","siid":2,"piid":2,"code":1,"ts":1615550038,"ret":0}]} length:98 bytes\x1b[0m'
2021-03-12 11:53:59  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:58.547 [D] miio_client_func: handle_command_ack_msg: {"id":33612776,"result":[{"did":"1041479927","siid":2,"piid":2,"code":1,"ts":1615550038,"ret":0}]}\x1b[0m'
2021-03-12 11:53:59  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:58.562 [D] ots: ots_down_rpc_delegate_ack(), 195, ack: {"id":33612776,"result":[{"did":"1041479927","siid":2,"piid":2,"code":1,"ts":1615550038,"ret":0}],"exe_time":110}, len: 113\x1b[0m'
2021-03-12 11:53:59  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:58.565 [D] miio_client_func: ot_agent_recv_handler_one(): fd:3, msg:{"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":2,"value":1,"tid":-1}],"id":173387} length:112 bytes\x1b[0m'
2021-03-12 11:53:59  DEBUG    gateway3      192.168.4.19 | Process props [{'did': '1041479927', 'siid': 2, 'piid': 2, 'value': 1, 'tid': -1}]
2021-03-12 11:53:59  DEBUG    gateway3      192.168.4.19 | Process Mesh Data for 1041479927: {'brightness': 1}
2021-03-12 11:53:59  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:58.566 [D] miio_client_rpc: call={"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":2,"value":1,"tid":-1}],"id":173387}\x1b[0m'
2021-03-12 11:53:59  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:58.672 [D] ots: ots_up_rpc_delegate_out_cb(), 289, {"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":2,"value":1,"tid":-1}],"id":173387}\x1b[0m'
2021-03-12 11:53:59  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:58.862 [D] ots: {"from":"","id":37709990,"method":"set_properties","params":[{"did":"1041479927","piid":2,"siid":2,"value":100}]}.\x1b[0m'
2021-03-12 11:53:59  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:58.893 [D] miio_client_func: method_local_broadcast_msg(), {"from":"","id":37709990,"method":"set_properties","params":[{"did":"1041479927","piid":2,"siid":2,"value":100}]}\x1b[0m'
2021-03-12 11:53:59  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:58.893 [D] miio_client_func: 3, msg: {"from":"","id":37709990,"method":"set_properties","params":[{"did":"1041479927","piid":2,"siid":2,"value":100}]},  len:113\x1b[0m'
2021-03-12 11:53:59  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:58.898 [D] miio_client_func: ot_agent_recv_handler_one(): fd:3, msg:{"id":37709990,"result":[{"did":"1041479927","siid":2,"piid":2,"code":1,"ts":1615550038,"ret":0}]} length:98 bytes\x1b[0m'
2021-03-12 11:53:59  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:58.899 [D] miio_client_func: handle_command_ack_msg: {"id":37709990,"result":[{"did":"1041479927","siid":2,"piid":2,"code":1,"ts":1615550038,"ret":0}]}\x1b[0m'
2021-03-12 11:53:59  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:59.002 [D] ots: ots_down_rpc_delegate_ack(), 195, ack: {"id":37709990,"result":[{"did":"1041479927","siid":2,"piid":2,"code":1,"ts":1615550038,"ret":0}],"exe_time":110}, len: 113\x1b[0m'
2021-03-12 11:54:00  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:59.113 [D] miio_client_func: ot_agent_recv_handler_one(): fd:3, msg:{"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":2,"value":71,"tid":-1}],"id":173388} length:113 bytes\x1b[0m'
2021-03-12 11:54:00  DEBUG    gateway3      192.168.4.19 | Process props [{'did': '1041479927', 'siid': 2, 'piid': 2, 'value': 71, 'tid': -1}]
2021-03-12 11:54:00  DEBUG    gateway3      192.168.4.19 | Process Mesh Data for 1041479927: {'brightness': 71}
2021-03-12 11:54:00  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:59.114 [D] miio_client_rpc: call={"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":2,"value":71,"tid":-1}],"id":173388}\x1b[0m'
2021-03-12 11:54:00  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:59.222 [D] ots: ots_up_rpc_delegate_out_cb(), 289, {"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":2,"value":71,"tid":-1}],"id":173388}\x1b[0m'
2021-03-12 11:54:00  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:59.663 [D] miio_client_func: ot_agent_recv_handler_one(): fd:3, msg:{"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":2,"value":100,"tid":-1}],"id":173389} length:114 bytes\x1b[0m'
2021-03-12 11:54:00  DEBUG    gateway3      192.168.4.19 | Process props [{'did': '1041479927', 'siid': 2, 'piid': 2, 'value': 100, 'tid': -1}]
2021-03-12 11:54:00  DEBUG    gateway3      192.168.4.19 | Process Mesh Data for 1041479927: {'brightness': 100}
2021-03-12 11:54:00  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:59.663 [D] miio_client_rpc: call={"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":2,"value":100,"tid":-1}],"id":173389}\x1b[0m'
2021-03-12 11:54:00  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:59.681 [D] ots: {"from":"","id":94267176,"method":"set_properties","params":[{"did":"1041479927","piid":2,"siid":2,"value":100}]}.\x1b[0m'
2021-03-12 11:54:00  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:59.772 [D] ots: ots_up_rpc_delegate_out_cb(), 289, {"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":2,"value":100,"tid":-1}],"id":173389}\x1b[0m'
2021-03-12 11:54:00  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:59.774 [D] miio_client_func: method_local_broadcast_msg(), {"from":"","id":94267176,"method":"set_properties","params":[{"did":"1041479927","piid":2,"siid":2,"value":100}]}\x1b[0m'
2021-03-12 11:54:00  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:59.774 [D] miio_client_func: 3, msg: {"from":"","id":94267176,"method":"set_properties","params":[{"did":"1041479927","piid":2,"siid":2,"value":100}]},  len:113\x1b[0m'
2021-03-12 11:54:00  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:59.780 [D] miio_client_func: ot_agent_recv_handler_one(): fd:3, msg:{"id":94267176,"result":[{"did":"1041479927","siid":2,"piid":2,"code":1,"ts":1615550039,"ret":0}]} length:98 bytes\x1b[0m'
2021-03-12 11:54:00  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:59.780 [D] miio_client_func: handle_command_ack_msg: {"id":94267176,"result":[{"did":"1041479927","siid":2,"piid":2,"code":1,"ts":1615550039,"ret":0}]}\x1b[0m'
2021-03-12 11:54:00  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:53:59.882 [D] ots: ots_down_rpc_delegate_ack(), 195, ack: {"id":94267176,"result":[{"did":"1041479927","siid":2,"piid":2,"code":1,"ts":1615550039,"ret":0}],"exe_time":109}, len: 113\x1b[0m'
2021-03-12 11:54:01  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:00.213 [D] miio_client_func: ot_agent_recv_handler_one(): fd:3, msg:{"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":2,"value":100,"tid":-1}],"id":173390} length:114 bytes\x1b[0m'
2021-03-12 11:54:01  DEBUG    gateway3      192.168.4.19 | Process props [{'did': '1041479927', 'siid': 2, 'piid': 2, 'value': 100, 'tid': -1}]
2021-03-12 11:54:01  DEBUG    gateway3      192.168.4.19 | Process Mesh Data for 1041479927: {'brightness': 100}
2021-03-12 11:54:01  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:00.214 [D] miio_client_rpc: call={"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":2,"value":100,"tid":-1}],"id":173390}\x1b[0m'
2021-03-12 11:54:01  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:00.322 [D] ots: ots_up_rpc_delegate_out_cb(), 289, {"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":2,"value":100,"tid":-1}],"id":173390}\x1b[0m'
2021-03-12 11:54:02  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:01.772 [D] ots: {"from":"","id":92863402,"method":"set_properties","params":[{"did":"1041479927","piid":3,"siid":2,"value":6094}]}.\x1b[0m'
2021-03-12 11:54:02  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:01.863 [D] miio_client_func: method_local_broadcast_msg(), {"from":"","id":92863402,"method":"set_properties","params":[{"did":"1041479927","piid":3,"siid":2,"value":6094}]}\x1b[0m'
2021-03-12 11:54:02  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:01.863 [D] miio_client_func: 3, msg: {"from":"","id":92863402,"method":"set_properties","params":[{"did":"1041479927","piid":3,"siid":2,"value":6094}]},  len:114\x1b[0m'
2021-03-12 11:54:02  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:01.869 [D] miio_client_func: ot_agent_recv_handler_one(): fd:3, msg:{"id":92863402,"result":[{"did":"1041479927","siid":2,"piid":3,"code":1,"ts":1615549744,"ret":0}]} length:98 bytes\x1b[0m'
2021-03-12 11:54:02  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:01.869 [D] miio_client_func: handle_command_ack_msg: {"id":92863402,"result":[{"did":"1041479927","siid":2,"piid":3,"code":1,"ts":1615549744,"ret":0}]}\x1b[0m'
2021-03-12 11:54:02  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:02.972 [D] ots: ots_down_rpc_delegate_ack(), 195, ack: {"id":92863402,"result":[{"did":"1041479927","siid":2,"piid":3,"code":1,"ts":1615549744,"ret":0}],"exe_time":110}, len: 113\x1b[0m'
2021-03-12 11:54:03  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:02.322 [D] ots: {"from":"","id":24673838,"method":"set_properties","params":[{"did":"1041479927","piid":3,"siid":2,"value":4870}]}.\x1b[0m'
2021-03-12 11:54:03  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:02.422 [D] miio_client_func: method_local_broadcast_msg(), {"from":"","id":24673838,"method":"set_properties","params":[{"did":"1041479927","piid":3,"siid":2,"value":4870}]}\x1b[0m'
2021-03-12 11:54:03  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:02.422 [D] miio_client_func: 3, msg: {"from":"","id":24673838,"method":"set_properties","params":[{"did":"1041479927","piid":3,"siid":2,"value":4870}]},  len:114\x1b[0m'
2021-03-12 11:54:03  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:02.427 [D] miio_client_func: ot_agent_recv_handler_one(): fd:3, msg:{"id":24673838,"result":[{"did":"1041479927","siid":2,"piid":3,"code":1,"ts":1615550042,"ret":0}]} length:98 bytes\x1b[0m'
2021-03-12 11:54:03  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:02.427 [D] miio_client_func: handle_command_ack_msg: {"id":24673838,"result":[{"did":"1041479927","siid":2,"piid":3,"code":1,"ts":1615550042,"ret":0}]}\x1b[0m'
2021-03-12 11:54:03  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:02.522 [D] ots: ots_down_rpc_delegate_ack(), 195, ack: {"id":24673838,"result":[{"did":"1041479927","siid":2,"piid":3,"code":1,"ts":1615550042,"ret":0}],"exe_time":110}, len: 113\x1b[0m'
2021-03-12 11:54:03  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:02.533 [D] miio_client_func: ot_agent_recv_handler_one(): fd:3, msg:{"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":3,"value":6094,"tid":-1}],"id":173391} length:115 bytes\x1b[0m'
2021-03-12 11:54:03  DEBUG    gateway3      192.168.4.19 | Process props [{'did': '1041479927', 'siid': 2, 'piid': 3, 'value': 6094, 'tid': -1}]
2021-03-12 11:54:03  DEBUG    gateway3      192.168.4.19 | Process Mesh Data for 1041479927: {'color_temp': 6094}
2021-03-12 11:54:03  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:02.533 [D] miio_client_rpc: call={"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":3,"value":6094,"tid":-1}],"id":173391}\x1b[0m'
2021-03-12 11:54:03  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:02.632 [D] ots: ots_up_rpc_delegate_out_cb(), 289, {"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":3,"value":6094,"tid":-1}],"id":173391}\x1b[0m'
2021-03-12 11:54:03  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:02.652 [D] ots: {"from":"","id":73366865,"method":"set_properties","params":[{"did":"1041479927","piid":3,"siid":2,"value":3816}]}.\x1b[0m'
2021-03-12 11:54:03  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:02.752 [D] miio_client_func: method_local_broadcast_msg(), {"from":"","id":73366865,"method":"set_properties","params":[{"did":"1041479927","piid":3,"siid":2,"value":3816}]}\x1b[0m'
2021-03-12 11:54:03  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:02.752 [D] miio_client_func: 3, msg: {"from":"","id":73366865,"method":"set_properties","params":[{"did":"1041479927","piid":3,"siid":2,"value":3816}]},  len:114\x1b[0m'
2021-03-12 11:54:03  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:02.758 [D] miio_client_func: ot_agent_recv_handler_one(): fd:3, msg:{"id":73366865,"result":[{"did":"1041479927","siid":2,"piid":3,"code":1,"ts":1615550042,"ret":0}]} length:98 bytes\x1b[0m'
2021-03-12 11:54:03  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:02.758 [D] miio_client_func: handle_command_ack_msg: {"id":73366865,"result":[{"did":"1041479927","siid":2,"piid":3,"code":1,"ts":1615550042,"ret":0}]}\x1b[0m'
2021-03-12 11:54:03  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:02.852 [D] ots: ots_down_rpc_delegate_ack(), 195, ack: {"id":73366865,"result":[{"did":"1041479927","siid":2,"piid":3,"code":1,"ts":1615550042,"ret":0}],"exe_time":110}, len: 113\x1b[0m'
2021-03-12 11:54:03  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:03.083 [D] miio_client_func: ot_agent_recv_handler_one(): fd:3, msg:{"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":3,"value":3816,"tid":-1}],"id":173392} length:115 bytes\x1b[0m'
2021-03-12 11:54:03  DEBUG    gateway3      192.168.4.19 | Process props [{'did': '1041479927', 'siid': 2, 'piid': 3, 'value': 3816, 'tid': -1}]
2021-03-12 11:54:03  DEBUG    gateway3      192.168.4.19 | Process Mesh Data for 1041479927: {'color_temp': 3816}
2021-03-12 11:54:03  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:03.083 [D] miio_client_rpc: call={"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":3,"value":3816,"tid":-1}],"id":173392}\x1b[0m'
2021-03-12 11:54:03  WARNING  mini_miio     192.168.4.19 | Can't send get_properties [{'did': '1041479927', 'siid': 2, 'piid': 1}]
2021-03-12 11:54:03  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:03.093 [D] ots: {"from":"","id":24666964,"method":"set_properties","params":[{"did":"1041479927","piid":3,"siid":2,"value":3000}]}.\x1b[0m'
2021-03-12 11:54:04  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:03.182 [D] ots: ots_up_rpc_delegate_out_cb(), 289, {"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":3,"value":3816,"tid":-1}],"id":173392}\x1b[0m'
2021-03-12 11:54:04  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:03.192 [D] miio_client_func: method_local_broadcast_msg(), {"from":"","id":24666964,"method":"set_properties","params":[{"did":"1041479927","piid":3,"siid":2,"value":3000}]}\x1b[0m'
2021-03-12 11:54:04  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:03.192 [D] miio_client_func: 3, msg: {"from":"","id":24666964,"method":"set_properties","params":[{"did":"1041479927","piid":3,"siid":2,"value":3000}]},  len:114\x1b[0m'
2021-03-12 11:54:04  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:03.198 [D] miio_client_func: ot_agent_recv_handler_one(): fd:3, msg:{"id":24666964,"result":[{"did":"1041479927","siid":2,"piid":3,"code":1,"ts":1615550042,"ret":0}]} length:98 bytes\x1b[0m'
2021-03-12 11:54:04  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:03.198 [D] miio_client_func: handle_command_ack_msg: {"id":24666964,"result":[{"did":"1041479927","siid":2,"piid":3,"code":1,"ts":1615550042,"ret":0}]}\x1b[0m'
2021-03-12 11:54:04  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:03.292 [D] ots: ots_down_rpc_delegate_ack(), 195, ack: {"id":24666964,"result":[{"did":"1041479927","siid":2,"piid":3,"code":1,"ts":1615550042,"ret":0}],"exe_time":109}, len: 113\x1b[0m'
2021-03-12 11:54:04  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:03.532 [D] ots: {"from":"","id":92172758,"method":"set_properties","params":[{"did":"1041479927","piid":3,"siid":2,"value":3000}]}.\x1b[0m'
2021-03-12 11:54:04  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:03.633 [D] miio_client_func: ot_agent_recv_handler_one(): fd:3, msg:{"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":3,"value":3000,"tid":-1}],"id":173393} length:115 bytes\x1b[0m'
2021-03-12 11:54:04  DEBUG    gateway3      192.168.4.19 | Process props [{'did': '1041479927', 'siid': 2, 'piid': 3, 'value': 3000, 'tid': -1}]
2021-03-12 11:54:04  DEBUG    gateway3      192.168.4.19 | Process Mesh Data for 1041479927: {'color_temp': 3000}
2021-03-12 11:54:04  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:03.633 [D] miio_client_rpc: call={"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":3,"value":3000,"tid":-1}],"id":173393}\x1b[0m'
2021-03-12 11:54:04  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:03.634 [D] miio_client_func: method_local_broadcast_msg(), {"from":"","id":92172758,"method":"set_properties","params":[{"did":"1041479927","piid":3,"siid":2,"value":3000}]}\x1b[0m'
2021-03-12 11:54:04  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:03.634 [D] miio_client_func: 3, msg: {"from":"","id":92172758,"method":"set_properties","params":[{"did":"1041479927","piid":3,"siid":2,"value":3000}]},  len:114\x1b[0m'
2021-03-12 11:54:04  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:03.639 [D] miio_client_func: ot_agent_recv_handler_one(): fd:3, msg:{"id":92172758,"result":[{"did":"1041479927","siid":2,"piid":3,"code":1,"ts":1615550043,"ret":0}]} length:98 bytes\x1b[0m'
2021-03-12 11:54:04  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:03.640 [D] miio_client_func: handle_command_ack_msg: {"id":92172758,"result":[{"did":"1041479927","siid":2,"piid":3,"code":1,"ts":1615550043,"ret":0}]}\x1b[0m'
2021-03-12 11:54:04  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:03.732 [D] ots: ots_up_rpc_delegate_out_cb(), 289, {"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":3,"value":3000,"tid":-1}],"id":173393}\x1b[0m'
2021-03-12 11:54:04  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:03.733 [D] ots: ots_down_rpc_delegate_ack(), 195, ack: {"id":92172758,"result":[{"did":"1041479927","siid":2,"piid":3,"code":1,"ts":1615550043,"ret":0}],"exe_time":111}, len: 113\x1b[0m'
2021-03-12 11:54:05  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:04.183 [D] miio_client_func: ot_agent_recv_handler_one(): fd:3, msg:{"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":3,"value":3000,"tid":-1}],"id":173394} length:115 bytes\x1b[0m'
2021-03-12 11:54:05  DEBUG    gateway3      192.168.4.19 | Process props [{'did': '1041479927', 'siid': 2, 'piid': 3, 'value': 3000, 'tid': -1}]
2021-03-12 11:54:05  DEBUG    gateway3      192.168.4.19 | Process Mesh Data for 1041479927: {'color_temp': 3000}
2021-03-12 11:54:05  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:04.183 [D] miio_client_rpc: call={"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":3,"value":3000,"tid":-1}],"id":173394}\x1b[0m'
2021-03-12 11:54:05  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:04.282 [D] ots: ots_up_rpc_delegate_out_cb(), 289, {"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":3,"value":3000,"tid":-1}],"id":173394}\x1b[0m'
2021-03-12 11:54:43  WARNING  mini_miio     192.168.4.19 | Can't send get_properties [{'did': '1041479927', 'siid': 2, 'piid': 1}]
2021-03-12 11:54:48  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:47.290 [D] ots: {"from":"","id":99222024,"method":"set_properties","params":[{"did":"1041479927","piid":1,"siid":2,"value":false}]}.\x1b[0m'
2021-03-12 11:54:48  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:47.342 [D] miio_client_func: method_local_broadcast_msg(), {"from":"","id":99222024,"method":"set_properties","params":[{"did":"1041479927","piid":1,"siid":2,"value":false}]}\x1b[0m'
2021-03-12 11:54:48  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:47.342 [D] miio_client_func: 3, msg: {"from":"","id":99222024,"method":"set_properties","params":[{"did":"1041479927","piid":1,"siid":2,"value":false}]},  len:115\x1b[0m'
2021-03-12 11:54:48  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:47.348 [D] miio_client_func: ot_agent_recv_handler_one(): fd:3, msg:{"id":99222024,"result":[{"did":"1041479927","siid":2,"piid":1,"code":1,"ts":1615549864,"ret":0}]} length:98 bytes\x1b[0m'
2021-03-12 11:54:48  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:47.348 [D] miio_client_func: handle_command_ack_msg: {"id":99222024,"result":[{"did":"1041479927","siid":2,"piid":1,"code":1,"ts":1615549864,"ret":0}]}\x1b[0m'
2021-03-12 11:54:48  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:47.402 [D] ots: ots_down_rpc_delegate_ack(), 195, ack: {"id":99222024,"result":[{"did":"1041479927","siid":2,"piid":1,"code":1,"ts":1615549864,"ret":0}],"exe_time":110}, len: 113\x1b[0m'
2021-03-12 11:54:48  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:47.633 [D] miio_client_func: ot_agent_recv_handler_one(): fd:3, msg:{"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":1,"value":false,"tid":-1}],"id":173402} length:116 bytes\x1b[0m'
2021-03-12 11:54:48  DEBUG    gateway3      192.168.4.19 | Process props [{'did': '1041479927', 'siid': 2, 'piid': 1, 'value': False, 'tid': -1}]
2021-03-12 11:54:48  DEBUG    gateway3      192.168.4.19 | Process Mesh Data for 1041479927: {'light': False}
2021-03-12 11:54:48  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:47.633 [D] miio_client_rpc: call={"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":1,"value":false,"tid":-1}],"id":173402}\x1b[0m'
2021-03-12 11:54:48  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:47.732 [D] ots: ots_up_rpc_delegate_out_cb(), 289, {"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":1,"value":false,"tid":-1}],"id":173402}\x1b[0m'
2021-03-12 11:54:53  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:52.132 [D] ots: {"from":"","id":80908142,"method":"set_properties","params":[{"did":"1041479927","piid":1,"siid":2,"value":true}]}.\x1b[0m'
2021-03-12 11:54:53  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:52.142 [D] miio_client_func: method_local_broadcast_msg(), {"from":"","id":80908142,"method":"set_properties","params":[{"did":"1041479927","piid":1,"siid":2,"value":true}]}\x1b[0m'
2021-03-12 11:54:53  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:52.142 [D] miio_client_func: 3, msg: {"from":"","id":80908142,"method":"set_properties","params":[{"did":"1041479927","piid":1,"siid":2,"value":true}]},  len:114\x1b[0m'
2021-03-12 11:54:53  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:52.148 [D] miio_client_func: ot_agent_recv_handler_one(): fd:3, msg:{"id":80908142,"result":[{"did":"1041479927","siid":2,"piid":1,"code":1,"ts":1615550087,"ret":0}]} length:98 bytes\x1b[0m'
2021-03-12 11:54:53  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:52.149 [D] miio_client_func: handle_command_ack_msg: {"id":80908142,"result":[{"did":"1041479927","siid":2,"piid":1,"code":1,"ts":1615550087,"ret":0}]}\x1b[0m'
2021-03-12 11:54:53  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:52.242 [D] ots: ots_down_rpc_delegate_ack(), 195, ack: {"id":80908142,"result":[{"did":"1041479927","siid":2,"piid":1,"code":1,"ts":1615550087,"ret":0}],"exe_time":109}, len: 113\x1b[0m'
2021-03-12 11:54:53  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:52.583 [D] miio_client_func: ot_agent_recv_handler_one(): fd:3, msg:{"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":1,"value":true,"tid":-1}],"id":173403} length:115 bytes\x1b[0m'
2021-03-12 11:54:53  DEBUG    gateway3      192.168.4.19 | Process props [{'did': '1041479927', 'siid': 2, 'piid': 1, 'value': True, 'tid': -1}]
2021-03-12 11:54:53  DEBUG    gateway3      192.168.4.19 | Process Mesh Data for 1041479927: {'light': True}
2021-03-12 11:54:53  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:52.583 [D] miio_client_rpc: call={"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":1,"value":true,"tid":-1}],"id":173403}\x1b[0m'
2021-03-12 11:54:53  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:54:52.682 [D] ots: ots_up_rpc_delegate_out_cb(), 289, {"method":"properties_changed","params":[{"did":"1041479927","siid":2,"piid":1,"value":true,"tid":-1}],"id":173403}\x1b[0m'
2021-03-12 11:55:22  WARNING  mini_miio     192.168.4.19 | Can't send get_properties [{'did': '1041479927', 'siid': 2, 'piid': 1}]
2021-03-12 11:55:25  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:55:25.035 [D] miio_client_func: ot_agent_recv_handler_one(): fd:3, msg:{"method":"_sync.ble_mesh_keep_alive","uptype":2,"params":[{"did":"1041479927","rssi":-40,"hops":0,"ts":1615550124}],"id":173411} length:129 bytes\x1b[0m'
2021-03-12 11:55:25  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:55:25.035 [D] miio_client_rpc: call={"method":"_sync.ble_mesh_keep_alive","uptype":2,"params":[{"did":"1041479927","rssi":-40,"hops":0,"ts":1615550124}],"id":173411}\x1b[0m'
2021-03-12 11:55:26  DEBUG    gateway3      192.168.4.19 | MQTT | log/miio b'\x1b[0;32m2021:03:12:19:55:25.132 [D] ots: ots_up_rpc_delegate_out_cb(), 289, {"method":"_sync.ble_mesh_keep_alive","uptype":2,"params":[{"did":"1041479927","rssi":-40,"hops":0,"ts":1615550124}],"id":173411}\x1b[0m'

**Comment by tuzhis** [comment]
> @AlexxIT really appreciate your help, but still not work.
> I found some differences：
> a. the brightness of piid': 2 is not 1-100,
> b. the value of'piid': 3 is always 6410.,no matter how the homeassistant is adjusted

It can be used after modification, thanks again
