### ISSUE TITLE
homeassistant 2021.7  device automation triggers

### ISSUE THREAD

**Issue by dscao** [AlexxIT/XiaomiGateway3#385]
Logger: homeassistant.config
Source: components/device_automation/__init__.py:91
First occurred: 01:32:05 (3 occurrences)
Last logged: 01:32:05

```
Invalid config for [automation]: Integration 'xiaomi_gateway3' does not support device automation triggers (See ?, line ?).
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 85, in async_get_device_automation_platform
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_gateway3/device_trigger.py", line 2, in <module>
    from homeassistant.components.device_automation import TRIGGER_BASE_SCHEMA
ImportError: cannot import name 'TRIGGER_BASE_SCHEMA' from 'homeassistant.components.device_automation' (/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/config.py", line 104, in _try_async_validate_config_item
    config = await async_validate_config_item(hass, config, full_config)
  File "/usr/src/homeassistant/homeassistant/components/automation/config.py", line 72, in async_validate_config_item
    config[CONF_TRIGGER] = await async_validate_trigger_config(
  File "/usr/src/homeassistant/homeassistant/helpers/trigger.py", line 49, in async_validate_trigger_config
    conf = await platform.async_validate_trigger_config(hass, conf)
  File "/usr/src/homeassistant/homeassistant/components/device_automation/trigger.py", line 17, in async_validate_trigger_config
    platform = await async_get_device_automation_platform(
  File "/usr/src/homeassistant/homeassistant/components/device_automation/__init__.py", line 91, in async_get_device_automation_platform
    raise InvalidDeviceAutomationConfig(
homeassistant.components.device_automation.exceptions.InvalidDeviceAutomationConfig: Integration 'xiaomi_gateway3' does not support device automation triggers
```

**Comment by dominguesg** [comment]
Same problem here. I have installed homeassistant core-2021.7.0 and supervisor-2021.06.8.

**Comment by nuznormal** [comment]
same here.
issue started after update to core-2021.7.0

**Comment by aferraz** [comment]
Hi, same for me

**Comment by MaoZ1993** [comment]
exactly the same issue here... only after updated 2021.7

**Comment by Aliskin-Papa** [comment]
Same here for Xiaomi switch

**Comment by zvldz** [comment]
```

**Comment by zvldz** [comment]
```
Rename device trigger base schema to DEVICE_TRIGGER_BASE_SCHEMA 
```

Replace in 'custom_components/xiaomi_gateway3/device_trigger.py' 'TRIGGER_BASE_SCHEMA' to 'DEVICE_TRIGGER_BASE_SCHEMA'

```
--- device_trigger.py.orig      2021-07-08 14:36:12.193019049 +0300
+++ device_trigger.py   2021-07-08 14:37:41.956014894 +0300
@@ -1,5 +1,5 @@
 import voluptuous as vol
-from homeassistant.components.device_automation import TRIGGER_BASE_SCHEMA
+from homeassistant.components.device_automation import DEVICE_TRIGGER_BASE_SCHEMA
 from homeassistant.components.homeassistant.triggers import \
     state as state_trigger
 from homeassistant.const import *
@@ -10,7 +10,7 @@
 from .core import zigbee
 from .sensor import BUTTON
 
-TRIGGER_SCHEMA = TRIGGER_BASE_SCHEMA.extend(
+TRIGGER_SCHEMA = DEVICE_TRIGGER_BASE_SCHEMA.extend(
     {
         vol.Required(CONF_TYPE): cv.string,
         vol.Required('action'): cv.string
```

**Comment by Aliskin-Papa** [comment]
> 
> ```
> Rename device trigger base schema to DEVICE_TRIGGER_BASE_SCHEMA 
> ```
> 
> Replace in 'custom_components/xiaomi_gateway3/device_trigger.py' 'TRIGGER_BASE_SCHEMA' to 'DEVICE_TRIGGER_BASE_SCHEMA'
> 
> ```
> --- device_trigger.py.orig      2021-07-08 14:36:12.193019049 +0300
> +++ device_trigger.py   2021-07-08 14:37:41.956014894 +0300
> @@ -1,5 +1,5 @@
>  import voluptuous as vol
> -from homeassistant.components.device_automation import TRIGGER_BASE_SCHEMA
> +from homeassistant.components.device_automation import DEVICE_TRIGGER_BASE_SCHEMA
>  from homeassistant.components.homeassistant.triggers import \
>      state as state_trigger
>  from homeassistant.const import *
> @@ -10,7 +10,7 @@
>  from .core import zigbee
>  from .sensor import BUTTON
>  
> -TRIGGER_SCHEMA = TRIGGER_BASE_SCHEMA.extend(
> +TRIGGER_SCHEMA = DEVICE_TRIGGER_BASE_SCHEMA.extend(
>      {
>          vol.Required(CONF_TYPE): cv.string,
>          vol.Required('action'): cv.string
> ```

Its realy work fine!

**Comment by MaoZ1993** [comment]
> From the changes in 2021.7
> 
> ```
> Rename device trigger base schema to DEVICE_TRIGGER_BASE_SCHEMA 
> ```
> 
> Replace in 'custom_components/xiaomi_gateway3/device_trigger.py' 'TRIGGER_BASE_SCHEMA' to 'DEVICE_TRIGGER_BASE_SCHEMA'
> 
> ```
> --- device_trigger.py.orig      2021-07-08 14:36:12.193019049 +0300
> +++ device_trigger.py   2021-07-08 14:37:41.956014894 +0300
> @@ -1,5 +1,5 @@
>  import voluptuous as vol
> -from homeassistant.components.device_automation import TRIGGER_BASE_SCHEMA
> +from homeassistant.components.device_automation import DEVICE_TRIGGER_BASE_SCHEMA
>  from homeassistant.components.homeassistant.triggers import \
>      state as state_trigger
>  from homeassistant.const import *
> @@ -10,7 +10,7 @@
>  from .core import zigbee
>  from .sensor import BUTTON
>  
> -TRIGGER_SCHEMA = TRIGGER_BASE_SCHEMA.extend(
> +TRIGGER_SCHEMA = DEVICE_TRIGGER_BASE_SCHEMA.extend(
>      {
>          vol.Required(CONF_TYPE): cv.string,
>          vol.Required('action'): cv.string
> ```

works for me!  core 2021.7.0 | supervisor 2021.06.8.

**Comment by dominguesg** [comment]
> From the changes in 2021.7
> 
> ```
> Rename device trigger base schema to DEVICE_TRIGGER_BASE_SCHEMA 
> ```
> 
> Replace in 'custom_components/xiaomi_gateway3/device_trigger.py' 'TRIGGER_BASE_SCHEMA' to 'DEVICE_TRIGGER_BASE_SCHEMA'
> 
> ```
> --- device_trigger.py.orig      2021-07-08 14:36:12.193019049 +0300
> +++ device_trigger.py   2021-07-08 14:37:41.956014894 +0300
> @@ -1,5 +1,5 @@
>  import voluptuous as vol
> -from homeassistant.components.device_automation import TRIGGER_BASE_SCHEMA
> +from homeassistant.components.device_automation import DEVICE_TRIGGER_BASE_SCHEMA
>  from homeassistant.components.homeassistant.triggers import \
>      state as state_trigger
>  from homeassistant.const import *
> @@ -10,7 +10,7 @@
>  from .core import zigbee
>  from .sensor import BUTTON
>  
> -TRIGGER_SCHEMA = TRIGGER_BASE_SCHEMA.extend(
> +TRIGGER_SCHEMA = DEVICE_TRIGGER_BASE_SCHEMA.extend(
>      {
>          vol.Required(CONF_TYPE): cv.string,
>          vol.Required('action'): cv.string
> ```

Working perfectly again! Thank you!

**Comment by PWMFI** [comment]
This is a plug-in problem, or a problem with the new version of HA

**Comment by dscao** [comment]
> From the changes in 2021.7
> 
> ```
> Rename device trigger base schema to DEVICE_TRIGGER_BASE_SCHEMA 
> ```
> 
> Replace in 'custom_components/xiaomi_gateway3/device_trigger.py' 'TRIGGER_BASE_SCHEMA' to 'DEVICE_TRIGGER_BASE_SCHEMA'
> 
> ```
> --- device_trigger.py.orig      2021-07-08 14:36:12.193019049 +0300
> +++ device_trigger.py   2021-07-08 14:37:41.956014894 +0300
> @@ -1,5 +1,5 @@
>  import voluptuous as vol
> -from homeassistant.components.device_automation import TRIGGER_BASE_SCHEMA
> +from homeassistant.components.device_automation import DEVICE_TRIGGER_BASE_SCHEMA
>  from homeassistant.components.homeassistant.triggers import \
>      state as state_trigger
>  from homeassistant.const import *
> @@ -10,7 +10,7 @@
>  from .core import zigbee
>  from .sensor import BUTTON
>  
> -TRIGGER_SCHEMA = TRIGGER_BASE_SCHEMA.extend(
> +TRIGGER_SCHEMA = DEVICE_TRIGGER_BASE_SCHEMA.extend(
>      {
>          vol.Required(CONF_TYPE): cv.string,
>          vol.Required('action'): cv.string
> ```

It's OK,  thinks.

**Comment by AlexxIT** [comment]
Fixed in latest master thanks to @aatrubilin

**Comment by sthorley** [comment]
@AlexxIT Is there a timeline for when this new release will be pushed? I've changed my automations to work use states but would be nice to regain the ability to use device automations.

**Comment by AlexxIT** [comment]
Fixed in latest release

**Comment by Nikitkin** [comment]
Hi! After automation related to such a bug in the latest version of HA (2021.9.7). Gateway firmware version 1.5.0_0102. Can someone tell me a solution?

Logger: homeassistant.config
Source: config.py:464
First occurred: 15:23:54 (1 occurrences)
Last logged: 15:23:54

Invalid config for [automation]: Integration 'xiaomi_gateway3' does not provide trigger support. Got OrderedDict([('default_config', {}), ('lovelace', OrderedDict([('mode', 'yaml')])), ('tts', [OrderedDict([('platform', 'google_translate')])]), ('scene', {}), ('recorder', OrderedDict([('db_url', 'mysql://hass:hass@core-mariadb/homeassistant?charset=utf8'), ('purge_keep_days', 3), ('include', OrderedDict([('domains', ['switch', 'light']), ('entities', ['sensor.maria_db_size', 'sensor.0x00158d0001581109_temperature', 'sensor.0x00158d000159c7e6_temperature', 'sensor.0x00158d0001dcd47e_temperatu.... (See /config/configuration.yaml, line 24).

**Comment by vanderwaltl** [comment]
Seems this Issue is back with release  - 
Core
2024.10.2
Supervisor
2024.10.0
Operating System
13.1
Frontend
20241002.3

**Triggers: Integration 'xiaomi_gateway3' does not support device automation triggers**
