### ISSUE TITLE
Unable to turn off ZHA mode

### ISSUE THREAD

**Issue by levkanm** [AlexxIT/XiaomiGateway3#934]
I turned on the ZHA mode before, and later wanted to turn it off，but after turning off the switch and waiting for a while, the ZHA integration still shows that it is working.
<img width="242" alt="屏幕截图 2023-01-20 013159" src="https://user-images.githubusercontent.com/105607530/213520148-2ceb07a0-aafe-4ffd-bd08-eb302068f0ff.png">
<img width="205" alt="屏幕截图 2023-01-20 013712" src="https://user-images.githubusercontent.com/105607530/213520164-860afcdf-98bd-4bb7-aa45-734e2c73a61d.png">
After that, I tried to re-flash the gateway firmware and reinstall the integration, and the ZHA integration finally showed that it could not connect.
<img width="208" alt="屏幕截图 2023-01-20 013638" src="https://user-images.githubusercontent.com/105607530/213521320-d29e1428-4351-4392-984a-c91410687789.png">
But after some time, the ZHA integration shows working again, but I did not turn on the ZHA mode of the gateway.

**Comment by AlexxIT** [comment]
What version of integration are you currently using?

**Comment by gt-levkan2002** [comment]
> What version of integration are you currently using?

v3.0-alpha.1

**Comment by AlexxIT** [comment]
Alpha has big changes on this point:
- Checkbox in settings do nothing (will be deleted)
- Zigbee chip firmware flashes via Gateway dropdown entity
- ZHA/z2m mode ready to connect full time 24/7

By default zigbee chip works with MiHome (on default zigbee firmware). When you connects to gw via ZHA or z2m - zigbee chip switchs from MiHome to TCP mode until next gateway reboot. ZHA and z2m both can work with default and with custom zigbee firmware. MiHome can work only with default zigbee firmware.

**Comment by gt-levkan2002** [comment]
> 



> Alpha has big changes on this point:
> 
> * Checkbox in settings do nothing (will be deleted)
> * Zigbee chip firmware flashes via Gateway dropdown entity
> * ZHA/z2m mode ready to connect full time 24/7
> 
> By default zigbee chip works with MiHome (on default zigbee firmware). When you connects to gw via ZHA or z2m - zigbee chip switchs from MiHome to TCP mode until next gateway reboot. ZHA and z2m both can work with default and with custom zigbee firmware. MiHome can work only with default zigbee firmware.

How do I get the gateway back to the default zigbee firmware?My gateway has been going offline occasionally lately, and I think it has something to do with ZHA mode.

> Alpha has big changes on this point:
> 
> * Checkbox in settings do nothing (will be deleted)
> * Zigbee chip firmware flashes via Gateway dropdown entity
> * ZHA/z2m mode ready to connect full time 24/7
> 
> By default zigbee chip works with MiHome (on default zigbee firmware). When you connects to gw via ZHA or z2m - zigbee chip switchs from MiHome to TCP mode until next gateway reboot. ZHA and z2m both can work with default and with custom zigbee firmware. MiHome can work only with default zigbee firmware.

How do I get the gateway back to the default zigbee firmware?My gateway has been going offline occasionally lately, and I think it has something to do with ZHA mode.

**Comment by AlexxIT** [comment]
> - Zigbee chip firmware flashes via Gateway dropdown entity

**Comment by osnwt** [comment]
Updated from 3-alpha to 3.0 release. Wanted to change back to Xiaomi mode. Cannot flash original Zigbee firmware.

I choose "Zigbee flash EZSP", "Firmware" (does not matter which one), the result: ERROR

Tried with old firmware (was recommended), now on the latest 1.5.4 - no difference.

**Comment by AlexxIT** [comment]
Try to reboot gateway and flash again. Try to flash Custom and later default fw. Check Hass logs for errors

**Comment by osnwt** [comment]
Done, no change:
```

2023-01-23 14:21:52.558 WARNING (MainThread) [custom_components.xiaomi_gateway3.core.mini_miio] 10.1.0.11 | Device offline
2023-01-23 14:23:34.543 ERROR (MainThread) [custom_components.xiaomi_gateway3.core.ezsp] 10.1.0.11 [FWUP] Can't update firmware
Traceback (most recent call last):
File "/config/custom_components/xiaomi_gateway3/core/ezsp.py", line 52, in update_zigbee_firmware
cur_fw = await read_firmware(host)
File "/config/custom_components/xiaomi_gateway3/core/ezsp.py", line 104, in read_firmware
await asyncio.wait_for(ezsp._probe(), timeout=10)
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
return fut.result()
File "/usr/local/lib/python3.10/site-packages/bellows/ezsp/__init__.py", line 74, in _probe
await self.connect(use_thread=False)
File "/usr/local/lib/python3.10/site-packages/bellows/ezsp/__init__.py", line 118, in connect
self._gw = await bellows.uart.connect(self._config, self, use_thread=use_thread)
File "/usr/local/lib/python3.10/site-packages/bellows/uart.py", line 397, in connect
protocol, _ = await _connect(config, application)
File "/usr/local/lib/python3.10/site-packages/bellows/uart.py", line 372, in _connect
baudrate=config[CONF_DEVICE_BAUDRATE],
KeyError: 'baudrate'
2023-01-23 14:23:34.968 ERROR (MainThread) [frontend.js.latest.202301100] :0:0 Script error.
```

**Comment by AlexxIT** [comment]
Thanks. I'll check. Maybe problem with latest Hass versions. This works near 2022.10 version

**Comment by osnwt** [comment]
Any updates on this issue?

Currently I am stuck at z2m mode which I can't switch back. As a last resort, I installed HAOS 9.1, HACS, downloaded GW3 2.1.2. But can't install the integration: Не удалось загрузить мастер настройки: {"message":"Invalid handler specified"}.

Also I tried to reflash zigbee chip manually using sx tool, but also without success. Thanks, the GW still works in z2m mode, but any solution or at least a manual workaround would be greatly appreciated.

**Comment by AlexxIT** [comment]
@osnwt fixed in latest master version. Will be in next release

**Comment by osnwt** [comment]
Excellent, waiting for it...

**Comment by osnwt** [comment]
Still no luck, but for other reason, see logs... What service should listen there?

```
10.1.0.11 [FWUP] Can't update firmware
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/ezsp.py", line 52, in update_zigbee_firmware
    cur_fw = await read_firmware(host)
  File "/config/custom_components/xiaomi_gateway3/core/ezsp.py", line 104, in read_firmware
    await asyncio.wait_for(ezsp._probe(), timeout=10)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/site-packages/bellows/ezsp/__init__.py", line 74, in _probe
    await self.connect(use_thread=False)
  File "/usr/local/lib/python3.10/site-packages/bellows/ezsp/__init__.py", line 118, in connect
    self._gw = await bellows.uart.connect(self._config, self, use_thread=use_thread)
  File "/usr/local/lib/python3.10/site-packages/bellows/uart.py", line 397, in connect
    protocol, _ = await _connect(config, application)
  File "/usr/local/lib/python3.10/site-packages/bellows/uart.py", line 368, in _connect
    transport, protocol = await zigpy.serial.create_serial_connection(
  File "/usr/local/lib/python3.10/site-packages/zigpy/serial.py", line 36, in create_serial_connection
    transport, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('10.1.0.11', 8889)

```

**Comment by AlexxIT** [comment]
@osnwt maybe you disable internet for the gateway?
Goto gateway telnet and run ps

**Comment by osnwt** [comment]
Tried to ping external servers. It gets IPv6 address instead of IPv4 and fails to reach it. On IPv4 the same server is reachable. So I'll try to disable IPv6 somewhere and retry.

**Comment by osnwt** [comment]
Seems something is wrong with the hub system.

I have no IPv6 in my LAN. Router uses few DNS servers, each of them returns both A and AAAA addresses:

```
# cat /etc/resolv.conf
nameserver 10.1.0.1
nameserver 93.100.1.2
nameserver 94.19.255.3

```

This obviously fails:

```
# ping google.com
PING google.com (2a00:1450:4010:c08::66): 56 data bytes
ping: sendto: Network is unreachable

```

But hub doesn't have any IPv6 addresses configured except link local which should not be used outside of LAN:

```
# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue
    link/ether 54:ef:44:3d:12:fd brd ff:ff:ff:ff:ff:ff
    inet 10.1.0.11/24 brd 10.1.0.255 scope global wlan0
       valid_lft forever preferred_lft forever
    inet6 fe80::56ef:44ff:fe3d:12fd/64 scope link
       valid_lft forever preferred_lft forever
3: wlan0-9: <BROADCAST,MULTICAST> mtu 1500 qdisc noop
    link/ether 54:ef:44:3d:12:fd brd ff:ff:ff:ff:ff:ff
4: tmp.wlan0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop
    link/ether 00:e0:4c:81:86:86 brd ff:ff:ff:ff:ff:ff
5: wlan0-1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop
    link/ether 00:e0:4c:81:86:86 brd ff:ff:ff:ff:ff:ff
6: wlan0-2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop
    link/ether 00:e0:4c:81:86:86 brd ff:ff:ff:ff:ff:ff
7: wlan0-3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop
    link/ether 00:e0:4c:81:86:86 brd ff:ff:ff:ff:ff:ff
8: wlan0-4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop
    link/ether 00:e0:4c:81:86:86 brd ff:ff:ff:ff:ff:ff
9: wlan0-5: <BROADCAST,MULTICAST> mtu 1500 qdisc noop
    link/ether 00:e0:4c:81:86:86 brd ff:ff:ff:ff:ff:ff
10: wlan0-6: <BROADCAST,MULTICAST> mtu 1500 qdisc noop
    link/ether 00:e0:4c:81:86:86 brd ff:ff:ff:ff:ff:ff
11: wlan0-7: <BROADCAST,MULTICAST> mtu 1500 qdisc noop
    link/ether 00:e0:4c:81:86:86 brd ff:ff:ff:ff:ff:ff
12: wlan0-8: <BROADCAST,MULTICAST> mtu 1500 qdisc noop
    link/ether 00:e0:4c:81:86:86 brd ff:ff:ff:ff:ff:ff
13: pwlan0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop
    link/ether 00:e0:4c:81:96:96 brd ff:ff:ff:ff:ff:ff
14: sit0: <NOARP> mtu 1480 qdisc noop
    link/sit 0.0.0.0 brd 0.0.0.0
15: eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop
    link/ether 00:12:34:56:78:90 brd ff:ff:ff:ff:ff:ff
16: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop
    link/ether 00:12:34:56:78:91 brd ff:ff:ff:ff:ff:ff

```

So it's an issue with the hub, why it uses IPv6 instead of IPv4... Have no idea yet how to fix it.

**Comment by osnwt** [comment]
I have some busybox binary in /data (perhaps, left from manual firmware updates). So tried it as well as original one from /bin. Here are results:

```
# /bin/busybox ping google.com
PING google.com (2a00:1450:4010:c08::8a): 56 data bytes
ping: sendto: Network is unreachable

# /data/busybox ping google.com
PING google.com (64.233.165.100): 56 data bytes
64 bytes from 64.233.165.100: seq=0 ttl=108 time=5.287 ms
64 bytes from 64.233.165.100: seq=1 ttl=108 time=5.323 ms
64 bytes from 64.233.165.100: seq=2 ttl=108 time=5.129 ms
^C
```

So internal busybox wants IPv6 and fails. But alternative busybox works. I tried to reflash another firmware (was on mgl03_1.5.4_0090_stock, now mgl03_1.5.0_0102_stock) - same issues.

Definitely it is not for this thread anymore, but I have no idea what to do.
Can all settings be reset to factory on the hub?

**Comment by AlexxIT** [comment]
You can download openmiio manually to gateway. But you will need to update it to latest version every time

**Comment by PlutoVYS** [comment]
> Still no luck, but for other reason, see logs... What service should listen there?
> 
> ```
> 10.1.0.11 [FWUP] Can't update firmware
> Traceback (most recent call last):
>   File "/config/custom_components/xiaomi_gateway3/core/ezsp.py", line 52, in update_zigbee_firmware
>     cur_fw = await read_firmware(host)
>   File "/config/custom_components/xiaomi_gateway3/core/ezsp.py", line 104, in read_firmware
.......
>   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
>     await self.sock_connect(sock, address)
>   File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
>     return await fut
>   File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
>     raise OSError(err, f'Connect call failed {address}')
> ConnectionRefusedError: [Errno 111] Connect call failed ('10.1.0.11', 8889)
> ```

I have same error:

 File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.212.213', 8889)

**Comment by osnwt** [comment]
> You can download openmiio manually to gateway. But you will need to update it to latest version every time

What and where to get and where to put?

Also, if you download it from an external server, maybe you can either somehow embed it into the integration, or let it download it to Home Assistant, then send to the hub, or as a last chance put a copy of firmware to an external server which does not have any IPv6 addresses. Say, ya.ru or google.com both have AAAA records and can't be pinged. github.com for me gives just A record and can be pinged via IPv4.

**Comment by AlexxIT** [comment]
There is no suitable protocol to send files from integration to gateway. You can find links in integration sources.
Shell folder

**Comment by AlexxIT** [comment]
You can enable integration debug logs and check if this msg

https://github.com/AlexxIT/XiaomiGateway3/blob/7596fc1d6c342fe9ba0e088bcb48aa65f42c31b2/custom_components/xiaomi_gateway3/core/ezsp.py#L22

exist there. And later check if any error exist in logs.

**Comment by Yuke-hd** [comment]
I had the same issue, lucky for me I have a DEV envrionment (raspberry pi running with HA pre-2022.10 version), I manually intalled v2.1.2, then in the integration config turned on and turn off "mode ZHA or z2m", then in my Prod envrionment, the gateway can stay in "mihome" mode no problem

**Comment by kkmaslowski** [comment]
I have the same error on 3.1.0:

```
2023-03-01 20:52:18.292 ERROR (bellows.thread_0) [bellows.uart] Lost serial connection: OSError('Server closed connection')
2023-03-01 20:52:18.295 ERROR (MainThread) [bellows.ezsp] NCP entered failed state. Requesting APP controller restart
2023-03-01 20:52:18.298 WARNING (MainThread) [bellows.thread] Attempted to use a closed event loop
2023-03-01 20:52:18.815 WARNING (MainThread) [bellows.zigbee.application] ControllerApplication reset unsuccessful: ConnectionRefusedError(111, "Connect call failed ('192.168.10.119', 8888)")
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bellows/zigbee/application.py", line 637, in _reset_controller_loop
    await self._reset_controller()
  File "/usr/local/lib/python3.10/site-packages/bellows/zigbee/application.py", line 658, in _reset_controller
    await self.connect()
  File "/usr/local/lib/python3.10/site-packages/bellows/zigbee/application.py", line 124, in connect
    self._ezsp = await bellows.ezsp.EZSP.initialize(self.config)
  File "/usr/local/lib/python3.10/site-packages/bellows/ezsp/__init__.py", line 101, in initialize
    await ezsp.connect(use_thread=zigpy_config[conf.CONF_USE_THREAD])
  File "/usr/local/lib/python3.10/site-packages/bellows/ezsp/__init__.py", line 118, in connect
    self._gw = await bellows.uart.connect(self._config, self, use_thread=use_thread)
  File "/usr/local/lib/python3.10/site-packages/bellows/uart.py", line 389, in connect
    protocol, connection_done = await thread.run_coroutine_threadsafe(
  File "/usr/local/lib/python3.10/site-packages/bellows/uart.py", line 368, in _connect
    transport, protocol = await zigpy.serial.create_serial_connection(
  File "/usr/local/lib/python3.10/site-packages/zigpy/serial.py", line 36, in create_serial_connection
    transport, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.10.119', 8888)
2023-03-01 20:52:19.312 ERROR (MainThread) [custom_components.xiaomi_gateway3.core.ezsp] 192.168.10.119 [FWUP] Can't update firmware
Traceback (most recent call last):
  File "/config/custom_components/xiaomi_gateway3/core/ezsp.py", line 52, in update_zigbee_firmware
    cur_fw = await read_firmware(host)
  File "/config/custom_components/xiaomi_gateway3/core/ezsp.py", line 104, in read_firmware
    await asyncio.wait_for(ezsp._probe(), timeout=10)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/site-packages/bellows/ezsp/__init__.py", line 74, in _probe
    await self.connect(use_thread=False)
  File "/usr/local/lib/python3.10/site-packages/bellows/ezsp/__init__.py", line 118, in connect
    self._gw = await bellows.uart.connect(self._config, self, use_thread=use_thread)
  File "/usr/local/lib/python3.10/site-packages/bellows/uart.py", line 397, in connect
    protocol, _ = await _connect(config, application)
  File "/usr/local/lib/python3.10/site-packages/bellows/uart.py", line 368, in _connect
    transport, protocol = await zigpy.serial.create_serial_connection(
  File "/usr/local/lib/python3.10/site-packages/zigpy/serial.py", line 36, in create_serial_connection
    transport, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.10.119', 8889)
2023-03-01 20:52:32.754 WARNING (SyncWorker_8) [custom_components.solarman.solarman] Querying inverter 1709992578 at 192.168.10.106:8899 failed on connection start with exception [OSError]



```

**Comment by Xmister** [comment]
I was facing a similar issue, and found out a few things:
* XiaomiGateway3 addon has to be running in HA, otherwise some needed processes won't start
* In the default Zigbee mode however `Lumi_Z3GatewayHost_MQTT` will interfere with the flash process so it will never finish. (It keep restarting and resetting zigbee)
* The integration uses the wrong open_miio arguments, which will not make it possible to flash the firmware.
* If you set up Zigbee2Mqtt in HA (and keep the XiaomiGateway3 addon running), it will be in the right state for the console flash to finish.

**Comment by kkmaslowski** [comment]
@igelbro how to flash it manually from console? Do you see that gateway works more stable on custom EZSP FW?

**Comment by igelbro** [comment]
@kkmaslowski 
https://github.com/zvldz/mgl03_fw/tree/main/zigbee

**Comment by igelbro** [comment]
@Xmister 
`If you set up Zigbee2Mqtt in HA (and keep the XiaomiGateway3 addon running), it will be in the right state for the console flash to finish.`
Not for me :(

**Comment by igelbro** [comment]
@kkmaslowski Don`t know.

**Comment by Xmister** [comment]
> @Xmister `If you set up Zigbee2Mqtt in HA (and keep the XiaomiGateway3 addon running), it will be in the right state for the console flash to finish.` Not for me :(

I'm sorry to hear that. It took about 5 minutes for the flash to complete for me. You can telnet to the device and see if `Lumi_Z3GatewayHost_MQTT` keeps restarting. In that case try to restart zigbee2mqtt.


> 
> Can I flash it if I use ZHA mode? I see that ncp-uart-sw_mgl03_6_7_8_z2m.gbl is for Zigbee2MQTT.

I think it should work with ZHA as well. I used 6.7.10 though.

> Do you see that gateway works more stable on custom EZSP FW?

For me it got rid of the Zigbee timeouts in Z2M.

**Comment by Xmister** [comment]
Maybe the device firmware also matters. I'm using 1.5.4.
How long did you wait for the flash to finish? Have you been checking `top` in another terminal to see what processes are running?

**Comment by AlexxIT** [comment]
I can confirm that flashing from Hass GUI works fine for:
- Gateway fw 1.5.4_0090
- Hass 2023.3.5
- Integration 3.1.0

If something doesn't work for you - maybe you have blocked internet for gateway or have problems with IPv6

**Comment by szymucha94** [comment]
> > @Xmister i tried to flash ncp-uart-sw_mgl03_6_7_10_z2m.gbl without success, it stuck after 'Sending ncp-uart-sw_mgl03_6_7_10_z2m.gbl, 1548 blocks: Give your local XMODEM receive command now' ![Zrzut ekranu z 2023-03-21 14-39-49](https://user-images.githubusercontent.com/910243/226626505-257f8ec7-53bb-4628-a4d1-aa3ab1fdbed5.png)
> 
> Try this:
> 
> 1.- Disable ZHA or stop Z2M. 2.- Reboot hub. 3.- Reload Gateway3 integration in HA. (Make sure "Xiaomi Multimode Gateway" entity is available) 4.- Enable ZHA or start Z2M. Make sure it is working. It will ensure HUB is in Z2M/ZHA mode. 5. Telnet your HUB. 6. Run flash script 7.- Repeat 1 to 5 until succeed
> 
> I successfully flashed mine on fifth try.

I gave up after 10 attempts. I also have the same problem.

**Comment by AlexxIT** [comment]
Try to flash from integration v3.2.1 GUI

**Comment by szymucha94** [comment]
> Try to flash from integration v3.2.1 GUI

already did yesterday multiple times. Always r
![err](https://user-images.githubusercontent.com/95378717/232311799-e4afc112-1bf4-4567-bcbb-81fa74b440b4.PNG)
esults in error:
![err_ha](https://user-images.githubusercontent.com/95378717/232311811-9dc81482-4c55-4bc1-9c0f-898170c108e2.PNG)
![manual](https://user-images.githubusercontent.com/95378717/23231182
![ver](https://user-images.githubusercontent.com/95378717/232311827-7ee73fe3-9247-4f4e-b487-714af4e17d84.PNG)
0-468dee4e-9e76-4fa3-be95-e95b2527ca53.PNG)

**Comment by AlexxIT** [comment]
Check integration debug logs. I think it just can't download openmiio app from GitHub. Maybe your Hass server has problem with internet

**Comment by szymucha94** [comment]
> Check integration debug logs. I think it just can't download openmiio app from GitHub. Maybe your Hass server has problem with internet

no, it doesn't. openmiio is running on the gateway so naturally it was downloaded.

**Comment by szymucha94** [comment]
@AlexxIT  what do you mean "check integration debug logs"? Output that I've sent is all that I see in HA logs.

**Comment by AlexxIT** [comment]
Whole update process in one function:
https://github.com/AlexxIT/XiaomiGateway3/blob/6c1499a0b49edbf723cf8bf7e3ec406d01ffe57a/custom_components/xiaomi_gateway3/core/ezsp.py#L45-L48

Are you sure you using latest integration version?

You can run `/data/openmiio_agent --log.level=info` and check app version
